version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    container_name: webapi
    ports:
      - "5000:80" # HTTP
      - "5001:80" # HTTPS

  webapi.database:
    image: postgres:latest
    container_name: webapi.database
    environment:
      - POSTGRES_DB=Football
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=29022004bd
    volumes:
      - ./.containers/Football-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
